//! NIST PQC KAT harness for HAWK-512.
//!
//! Reproduces the NIST KAT generation procedure from PQCgenKAT_sign.c:
//!   1. Init AES-CTR-DRBG with entropy_input = [0..48).
//!   2. For i in 0..NUM_CASES:
//!        a. seed = drbg.generate(48)
//!        b. mlen = 33 * (i + 1); msg = drbg.generate(mlen)
//!        c. Init a per-case DRBG from seed.
//!        d. Generate keypair.
//!        e. Sign.
//!        f. Verify.
//!
//! Task 27. Currently validates that our keygen/sign/verify are
//! self-consistent over the NIST KAT sequence. Byte-exact cross-check
//! against the C reference is in the cross_check proptest suite.

#[path = "aes_ctr_drbg.rs"]
mod aes_ctr_drbg;

use aes_ctr_drbg::AesCtrDrbg;
use pqe_hawk::HawkKeypair;

/// Number of KAT cases to exercise. Full NIST suite is 100; keep low for CI
/// (each case takes ~1 s for keygen + sign + verify).
const NUM_CASES: usize = 5;

/// Thin adapter: wraps `AesCtrDrbg` so it can be passed to `HawkKeypair::generate`
/// and `HawkSecretKey::sign`, which accept `impl rand::RngCore`.
struct DrbgRng {
    drbg: AesCtrDrbg,
}

impl rand::RngCore for DrbgRng {
    fn next_u32(&mut self) -> u32 {
        let mut b = [0u8; 4];
        self.fill_bytes(&mut b);
        u32::from_le_bytes(b)
    }

    fn next_u64(&mut self) -> u64 {
        let mut b = [0u8; 8];
        self.fill_bytes(&mut b);
        u64::from_le_bytes(b)
    }

    fn fill_bytes(&mut self, dst: &mut [u8]) {
        self.drbg.generate(dst);
    }

    fn try_fill_bytes(&mut self, dst: &mut [u8]) -> Result<(), rand::Error> {
        self.drbg.generate(dst);
        Ok(())
    }
}

/// Build a per-case DRBG from the 48-byte seed extracted by the master DRBG.
///
/// In the NIST PQC KAT harness (`PQCgenKAT_sign.c`) the inner loop calls
/// `randombytes_init(seed, NULL, 256)` where `seed` is the 48-byte value
/// pulled from the master DRBG. Our `AesCtrDrbg::new` takes a 48-byte
/// entropy input directly, which matches that call.
fn drbg_from_kat_seed(seed: &[u8; 48]) -> AesCtrDrbg {
    AesCtrDrbg::new(seed)
}

/// Self-consistency check: NIST KAT generation procedure, Rust-only.
///
/// Runs `NUM_CASES` iterations of the NIST KAT loop.  For each case we
/// verify that `sign` produces a signature our own `verify` accepts.  This
/// confirms that our keygen/sign/verify are mutually consistent when driven
/// by the exact byte sequence the NIST harness would feed them.
#[test]
fn nist_kat_self_consistent() {
    // Master DRBG: entropy_input = [0, 1, 2, ..., 47].
    let master_entropy: [u8; 48] = std::array::from_fn(|i| i as u8);
    let mut master = AesCtrDrbg::new(&master_entropy);

    for i in 0..NUM_CASES {
        // Step (a): extract per-case seed.
        let mut seed = [0u8; 48];
        master.generate(&mut seed);

        // Step (b): extract message bytes. mlen = 33 * (i + 1).
        let mlen = 33 * (i + 1);
        let mut msg = vec![0u8; mlen];
        master.generate(&mut msg);

        // Step (c): initialise per-case DRBG.
        let case_drbg = drbg_from_kat_seed(&seed);
        let mut rng = DrbgRng { drbg: case_drbg };

        // Step (d): keygen.
        let kp = HawkKeypair::generate(&mut rng);

        // Step (e): sign.
        let sig = kp
            .secret
            .sign(&msg, &mut rng)
            .unwrap_or_else(|e| panic!("KAT case {i}: sign failed: {e}"));

        // Step (f): verify.
        assert!(
            kp.public.verify(&msg, &sig).is_ok(),
            "KAT case {i}: verify should accept our own signature"
        );
    }
}

/// Byte-exact pin of NIST KAT case 0 public key and secret key against the C
/// reference. Signature nonce matching is not pinned here because the signing
/// nonce depends on the exact RNG byte consumption after keygen; that is
/// validated by the FFI cross-check suite (`ffi_hawk_keypair_encoded_matches`,
/// `ffi_verify_accepts_rust_signature`).
///
/// Reference values generated by compiling and running the vendored
/// `c-reference/hawk-512/PQCgenKAT_sign.c` with
/// `entropy_input = [0, 1, 2, ..., 47]`.
#[test]
fn nist_kat_pins_case_0() {
    let master_entropy: [u8; 48] = std::array::from_fn(|i| i as u8);
    let mut master = AesCtrDrbg::new(&master_entropy);

    let mut seed = [0u8; 48];
    master.generate(&mut seed);

    let mlen = 33usize;
    let mut msg = vec![0u8; mlen];
    master.generate(&mut msg);

    let mut rng = DrbgRng {
        drbg: drbg_from_kat_seed(&seed),
    };
    let kp = HawkKeypair::generate(&mut rng);
    let sig = kp
        .secret
        .sign(&msg, &mut rng)
        .expect("case 0 sign should succeed");

    let rust_pk = kp.public.to_bytes().expect("encode_public");
    let rust_sk = kp.secret.to_bytes();

    assert_eq!(rust_pk.as_slice(), CASE_0_PK, "pk mismatch");
    assert_eq!(rust_sk.as_slice(), CASE_0_SK, "sk mismatch");
    // Verify that the Rust-generated signature is valid.
    assert!(
        kp.public.verify(&msg, &sig).is_ok(),
        "Rust verify should accept Rust signature on KAT case 0"
    );
}

const CASE_0_PK: &[u8] = include_bytes!("kat_vectors/case_0_pk.bin");
const CASE_0_SK: &[u8] = include_bytes!("kat_vectors/case_0_sk.bin");
